### PR TITLE
Upgrade to GnuRadio 3.7

### PR DESCRIPTION
**Pull request by dadopap**
Hi have updated the source to be installed in gnuradio 3.7

tested in ubuntu 14.04

### CODE REVIEW

**Comment by nazmibojan** [comment]
I have installed gr-aistx using cmake, make and make install but when I opened the .grc files of AIS_TX.grc I got this following error:

<<< Welcome to GNU Radio Companion 3.7.2.1 >>>

Loading: "/home/totos/Desktop/ais-master/AiS_TX.grc"

> > > Error: Block key "AISTX_Build_Frame" not found in Platform - grc(GNU Radio Companion)
> > > Error: Block key "AISTX_Build_Frame" not found in Platform - grc(GNU Radio Companion)
> > > Error: Connection between AISTX_Build_Frame_0(0) and digital_gmsk_mod_0(0) could not be made.
> > >     source block id "AISTX_Build_Frame_0" not in block ids
> > > Error: Connection between AISTX_Build_Frame_1(0) and digital_gmsk_mod_0_0(0) could not be made.
> > >     source block id "AISTX_Build_Frame_1" not in block ids
> > > Done

Showing: "/home/totos/Desktop/ais-master/AiS_TX.grc"

Can you help me please?
Thanks, Nazmi.

**Comment by dadopap** [comment]
Hi

This happened to me as well. The problem is that the make install doesn't copy the grc blocks (xml format) into the right directory.

You need to find out where gnuradio keeps its modules (just run "locate blocks |grep grc" or something similar), usually it is in /usr/local/share/gnuradio/blocks. Then copy the AIS xml blocks into that directory. That should do it.

Let me know if you succeed.

Cheers
dadopap

**Comment by nazmibojan** [comment]
Hi dadopap,

Thank you for sharing. It works!

But I found another problem when I run grc to usrp:
Generating: "/home/totos/Desktop/ais-master/top_block.py"

Generating: "/home/totos/Desktop/ais-master/top_block.py"

Executing: "/home/totos/Desktop/ais-master/top_block.py"

linux; GNU C++ version 4.8.2; Boost_105400; UHD_003.005.005-0-unknown

Traceback (most recent call last):
  File "/home/totos/Desktop/ais-master/top_block.py", line 19, in <module>
    import AISTX
ImportError: No module named AISTX

Hope you can help us to solve this problem.
Thanks.

Regards, Nazmi

**Comment by dadopap** [comment]
Hi

yes that has to do with the python path

Solving this is quite easy, you need to make sure that AISTX is in the pythonpath.

in my installation AISTX is located in

/usr/local/lib64/python2.7/site-packages/AISTX

cheers

**Comment by ghost** [comment]
I was able to fix #3 by adding 
`${GNURADIO_RUNTIME_INCLUDE_DIRS}/gnuradio/swig`
at line 114 of gr-aistx/CMakeLists.txt

Would be good to include before merge.

**Comment by embyte0** [comment]
Already merged, together with the other pull request. Thanks again.

**Pull request closed without merging**
